version: '3'
services:
  poll:
    build: ./poll/.
    restart: always
    env_file:
      - .env
    ports:
    - "5000:80"
    networks: 
      - poll-tier
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks: 
      - poll-tier
      - back-tier
  worker:
    restart: always
    build: ./worker/.
    env_file:
      - .env
    networks: 
      - back-tier
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks: 
      - result-tier
      - back-tier
  result:
    restart: always
    build: ./result/.
    env_file:
      - .env
    ports:
      - "5001:80"
    networks: 
      - result-tier

networks:
    poll-tier:
    result-tier:
    back-tier:
volumes:
    db-data: